services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # app:
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydb;Username=myuser;Password=mypassword
  #   ports:
  #     - "8080:80"
  #   restart: unless-stopped

volumes:
  pgdata:
